# Site settings
author: P. Cairo
title: Part-Time FlatIron Software Engineering Blog
header-img: img/home-bg.png
email: pcairo_90@outlook.com
copyright_name: P. Cairo
description: > # this means to ignore newlines until "baseurl:"
  Tech Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: pamcakez5
github_username:  piinkpantherpam

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
